/**
 * The one place a country list is defined in this codebase. Every form
 * that needs country selection (Country of Birth, Nationality, Country
 * of Residence, Previous Education Country, ...) reads from here via
 * <CountrySelect> (src/components/CountrySelect.tsx) or getCountries()
 * (./getCountries.ts) — never its own inline array.
 *
 * Not exhaustive of every ISO country; extending it is a one-line change
 * here rather than a hunt through every form that uses it.
 */
export const COUNTRIES = [
  "Cameroon",
  "Nigeria",
  "Chad",
  "Central African Republic",
  "Equatorial Guinea",
  "Gabon",
  "Republic of the Congo",
  "Democratic Republic of the Congo",
  "Benin",
  "Togo",
  "Ghana",
  "Ivory Coast",
  "Senegal",
  "Mali",
  "Burkina Faso",
  "Niger",
  "Guinea",
  "Sierra Leone",
  "Liberia",
  "The Gambia",
  "Guinea-Bissau",
  "Mauritania",
  "Morocco",
  "Algeria",
  "Tunisia",
  "Libya",
  "Egypt",
  "Sudan",
  "South Sudan",
  "Ethiopia",
  "Eritrea",
  "Somalia",
  "Kenya",
  "Uganda",
  "Rwanda",
  "Burundi",
  "Tanzania",
  "Zambia",
  "Malawi",
  "Mozambique",
  "Zimbabwe",
  "Botswana",
  "Namibia",
  "South Africa",
  "Angola",
  "Madagascar",
  "United States",
  "Canada",
  "United Kingdom",
  "France",
  "Germany",
  "Belgium",
  "Switzerland",
  "Italy",
  "Spain",
  "Portugal",
  "Netherlands",
  "Sweden",
  "China",
  "India",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Turkey",
  "Lebanon",
  "Brazil",
  "Other",
] as const;

export type Country = (typeof COUNTRIES)[number];
