import "server-only";
import { createReadStream } from "node:fs";
import { mkdir, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { env } from "@/server/config/env";

/**
 * Where file bytes live. Everything above this interface works with
 * storage keys and the `files` table only, so moving to object storage
 * (S3, R2, MinIO, Azure Blob) means adding a driver here and setting
 * STORAGE_DRIVER — no change to services or routes.
 */
export interface StorageDriver {
  readonly name: string;
  put(key: string, data: Uint8Array, contentType: string): Promise<void>;
  /** A web stream of the content, or null if the key doesn't exist. */
  get(key: string): Promise<ReadableStream<Uint8Array> | null>;
  delete(key: string): Promise<void>;
  /** Cheap readiness check for /api/health. */
  check(): Promise<void>;
}

/**
 * Local disk under STORAGE_LOCAL_DIR. Right for development and for a
 * single server with a persistent volume; not for serverless hosting,
 * where the disk doesn't survive between requests.
 */
class LocalDiskDriver implements StorageDriver {
  readonly name = "local";
  // Runtime data, not code: keep the bundler from tracing it into the deployment.
  private readonly root = path.resolve(/*turbopackIgnore: true*/ process.cwd(), env.STORAGE_LOCAL_DIR);

  private resolve(key: string): string {
    // Keys are generated by the file service, but never trust a path join.
    const full = path.resolve(this.root, key);
    if (!full.startsWith(this.root + path.sep)) throw new Error(`Storage key escapes the storage root: ${key}`);
    return full;
  }

  async put(key: string, data: Uint8Array) {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    // Write then rename, so a crash mid-write never leaves a half file under the real key.
    const tmp = `${full}.${process.pid}.tmp`;
    await writeFile(tmp, data);
    await rename(tmp, full);
  }

  async get(key: string) {
    const full = this.resolve(key);
    try {
      await stat(full);
    } catch {
      return null;
    }
    return Readable.toWeb(createReadStream(full)) as ReadableStream<Uint8Array>;
  }

  async delete(key: string) {
    await rm(this.resolve(key), { force: true });
  }

  async check() {
    await mkdir(this.root, { recursive: true });
  }
}

const KEY = Symbol.for("cheeta-aosa.storage");
const g = globalThis as unknown as { [KEY]?: StorageDriver };

export function getStorage(): StorageDriver {
  if (!g[KEY]) {
    switch (env.STORAGE_DRIVER) {
      case "local":
        g[KEY] = new LocalDiskDriver();
        break;
    }
  }
  return g[KEY]!;
}
